### PR TITLE
Add initial databricks support

### PR DESCRIPTION
**Pull request by zerodarkzone**
Hi,

I've added databriccks support. I have not been able to test everything . But for now it looks like it is working.

### CODE REVIEW

**Comment by eakmanrq** [comment]
Wow thanks @zerodarkzone! Since this doesn't have test coverage I will add a new section to the README that outlines in-development engines and put this and Redshift under that. I will do that after we get this merged in. 

I approved CI/CD in your PR. The error you are seeing row now is because this line doesn't include Databricks: https://github.com/eakmanrq/sqlframe/blob/35325088b2b82cc866e7f135bb0ccdb46317da26/Makefile#L1-L2

**Comment by zerodarkzone** [comment]
Hi,
I've updated the makefile. Just let me know if something else needs to be modified.

**Comment by eakmanrq** [comment]
Can you update documentation to list Databricks as an in development engine? I just did this for Redshift so you can match what I did there: https://github.com/eakmanrq/sqlframe/pull/208

Also your latest error suggest that you needed to use tab instead of spaces in the Makefile (nuance of makefiles) on the line that adds the stubs: 
```
Makefile:36: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.
```

**Comment by zerodarkzone** [comment]
Hi,
I've just added the documentation and also fixed the stubs problem.

**Comment by eakmanrq** [comment]
Documentation looks great! 

Looks like a style issue now: https://github.com/eakmanrq/sqlframe/actions/runs/12013465146/job/33518166903?pr=207

**Comment by zerodarkzone** [comment]
Hi, I think I fixed the style issues.
```
make style
pre-commit run --all-files
ruff.....................................................................Passed
ruff-format..............................................................Passed
mypy.....................................................................Passed

```

**Review by eakmanrq — APPROVED** [review]

**Pull request merged**
